### ISSUE TITLE
На доп. баллы

### ISSUE THREAD

**Issue by Andy-Messer** [AleshinAndrei/PyGame_Project#1]
Смотри проект написан чисто, предлагаю на доп баллы реализовать поддержку таблицы рекордов
И вторым пунктом таймер на прохождение лабиринта.

**Comment by Andy-Messer** [comment]
И еще, когда человечек появляется на поле не очень сразу понятно, что делать. Добавь всплывающую надпись "Найдите кубок"!

**Comment by AleshinAndrei** [comment]
Сделано!

**Comment by Andy-Messer** [comment]
Так, а ты можешь топ очистить, потому что попасть в него за 1 секунду нереально, а хочется видеть результаты(

**Comment by Andy-Messer** [comment]
И еще, кубок в верхнем левом углу, так и предполагался?

**Comment by Andy-Messer** [comment]
и организуй немного код: документацию переноси в директорию doc, main.py в нем оставляешь только запуск игры, класс игры выносишь в src/ аналогично отрисовку стен и земли. рекорды оставь рядом с main

**Comment by Andy-Messer** [comment]
задокументируй код, может придется что-то вынести в отельные функции, чтобы одна функция несла в себе одну идею, например: отрисовка стен, то там ничего лишнего(это не займет больше 30 минут на исправление)

**Comment by Andy-Messer** [comment]
Я уже поставлю баллы, просто хочу, чтобы всё было идеально

**Comment by Andy-Messer** [comment]
И напиши нормальный ридми, если что документируем вот в таком стиле https://doxygen.nl/manual/docblocks.html (вот пример https://github.com/Andy-Messer/formal-languages-practice-2/blob/main/earley_parser/grammar.py)

**Comment by AleshinAndrei** [comment]
Доделал

**Comment by AleshinAndrei** [comment]
> И еще, кубок в верхнем левом углу, так и предполагался?

Да, в качестве отладки (надо же как-то побить рекорд за 3 секунды)
